### ISSUE TITLE
Snowflake in version 6.7.1 does not work

### ISSUE THREAD

**Issue by wreps8Owt** [Gedsh/InviZible#266] opened 2024-06-19 13:11 UTC
Snowflake in F-Droid stable version 6.7.1 does not work, while snowflake in Beta v2.2.7 works fine. Is it possible to release a new stable version with working snowflake bridge based on Beta v2.2.7?

**Comment by Gedsh** [comment] 2024-06-19 20:01
You can try the stable version 6.7.1 that is built by me and you will see that it also works fine. https://github.com/Gedsh/InviZible/releases/tag/v6.7.1-stable So the problem is not with the version, but with the F-Droid build. They do it on their own.

I checked the F-Droid version and didn't find anything odd. So currently I don't know why it doesn't work with snowflake bridge and how to fix it. I don't have access to their build process.

**Comment by Gedsh** [comment] 2024-07-27 17:25
@wreps8Owt I have probably found the issue. The f-droid version uses the original snowflake. Other versions use my fork with one small change intended to better circumvent censorship. Can you confirm that the latest beta 2.3.0 works with snowflake and f-droid version 6.7.1 does not? That way, I can suggest these changes to the Tor project if they prove effective.

**Comment by wreps8Owt** [comment] 2024-07-27 17:38
> Can you confirm that the latest beta 2.3.0 works with snowflake and f-droid version 6.7.1 does not? That way, I can suggest these changes to the Tor project if they prove effective.
>
Confirmed.

**Comment by Gedsh** [comment] 2024-07-27 17:44
Thank you! Could you also check the Tor browser and Orbot with snowflake bridges to confirm that my changes are effective?

**Comment by wreps8Owt** [comment] 2024-07-27 18:01
> Thank you! Could you also check the Tor browser and Orbot with snowflake bridges to confirm that my changes are effective?
>
Both Tor browser and Orbot work with snowflake bridge.

**Comment by Gedsh** [comment] 2024-07-27 18:09
Thanks. This means that the problem is most probably in the snowflake version. I will provide the latest available commit for the next f-droid build.

**Comment by Gedsh** [comment] 2024-09-21 17:29
This should be fixed in version 6.8.0

**Closed by Gedsh** 2024-09-21 17:29 UTC
