### ISSUE TITLE
[FeatureRequest]Add PCAPdroid like UI and functionality

### ISSUE THREAD

**Issue by Rexadev** [Gedsh/InviZible#201] opened 2023-03-19 16:30 UTC
https://github.com/emanuele-f/PCAPdroid

1. App Icons
2. Options to Filter by App, IP
3. See Connection details like domain,IP, Port, Protocol
4. See Detailed view - UDP/TCP, Country, ASN

**Comment by Gedsh** [comment] 2023-03-24 16:29
Duplicate of https://github.com/Gedsh/InviZible/issues/131

**Closed by Gedsh** 2023-03-24 16:29 UTC

**Comment by Rexadev** [comment] 2023-03-24 16:55
> Duplicate of #131

I think my request is different

**Comment by Gedsh** [comment] 2023-03-25 16:15
Since the logs are stored in memory, I cannot implement what you are asking for. This will be an OOM error.

InviZible is designed for privacy and security. Therefore, it should be as reliable as possible. There is no any reason to reduce reliability for the sake of good-looking logs.
