### ISSUE TITLE
Tor bridge error

### ISSUE THREAD

**Issue by salarmg** [Gedsh/InviZible#25] opened 2020-02-28 19:44 UTC
Hi im using Xiaomi mi9 and Snapdragon 855
After enable tor bridge :

![Screenshot_2020-02-28-23-06-16-368_pan alexander tordnscrypt](https://user-images.githubusercontent.com/36221095/75581892-aee7e180-5a7f-11ea-92d9-02a3abb710c4.jpg)

Build version 0.6.8 ARM64

**Comment by salarmg** [comment] 2020-02-28 19:47
installed ARM7v and :(

![Screenshot_2020-02-28-23-16-42-247_pan alexander tordnscrypt](https://user-images.githubusercontent.com/36221095/75582277-78f72d00-5a80-11ea-89cc-3e8f873ef6fb.jpg)

**Comment by Gedsh** [comment] 2020-02-28 20:17
Duplicate of #22

**Closed** 2020-03-06 16:21 UTC
