### ISSUE TITLE
Possibility to integrate Wireguard client additionally to TOR, I2P and DNSCrypt for self-hosted server connection.

### ISSUE THREAD

**Issue by beevariant** [Gedsh/InviZible#294] opened 2024-09-20 13:38 UTC
Hello Gedsh,

First of all, thank you for the great work you do on this project. I use your application on a daily basis and have happily donated.

I'd like to propose the idea of integrating Wireguard compatibility. My Umbrel server runs a Wireguard server for communication and application interaction. The aim is to use Invizible as my exclusive VPN solution, eliminating the need to switch in my Android VPN settings when communicating with my Umbrel server.

I know other self-hosted servers, like Star-9, also feature Wireguard integration. I'm confident I'm not the only one who would value this feature, potentially making Invizible the exclusive VPN solution.

Thank you for considering this suggestion.

The babarian dude.

**Comment by Gedsh** [comment] 2024-09-21 17:21
Hello,

Thanks for the suggestion and for supporting the project! But currently I have no plans on adding new networks or any VPN solutions to InviZible.

**Comment by Gedsh** [comment] 2024-09-21 17:23
Duplicate of https://github.com/Gedsh/InviZible/issues/254

**Closed by Gedsh** 2024-09-21 17:23 UTC
