### ISSUE TITLE
Unavailable to contact remote lists with 'block connections without VPN' enabled

### ISSUE THREAD

**Issue by Gl17chV** [Gedsh/InviZible#311] opened 2024-10-31 19:41 UTC
Well the title says it all, it is not available to add or update remote lists if the option 'block connections without VPN' is activated on system settings (no custom ROM)

**Comment by Gl17chV** [comment] 2024-11-01 04:57
Yes, DNScrypt remote lists, sorry. I can't added or update it.

**Comment by Gedsh** [comment] 2024-11-01 21:32
> I can't added or update it.

What does it mean? Do you not see the appropriate options in the menu? Do you see some kind of error? Something else?

**Comment by Gl17chV** [comment] 2024-11-02 03:40
As I said, can't connect to the remote lists, they don't download, they don't contact.

![Screenshot_2024-11-01-21-34-58](https://github.com/user-attachments/assets/7db7b49a-9c6d-4cc2-bb1d-d1474b26765d)

**Comment by Gedsh** [comment] 2024-11-03 20:01
What is your phone and android version? Do you use a custom rom?

**Comment by Gl17chV** [comment] 2024-11-06 03:08
I tried it on three devices.

ZTE Blade V9 Vita - Android 8

Hisense v40 - Android 10

Infinix Hot 30i - Android 12

maybe it's a problem with my ISP, I've been having problems.

**Comment by Gedsh** [comment] 2024-11-06 11:38
> maybe it's a problem with my ISP

Most probably the problem is incorrect handling of blocking connections without VPN option. I've checked and found no problem on a Samsung phone, but I can reproduce the issue on a custom rom. Have you enabled compatibility mode in common settings on the above mentioned phones or does VPN mode work correctly without this option? I mean when the block connections without VPN option is disabled.

**Comment by Gl17chV** [comment] 2024-11-07 02:19
Still does not work with compatibility mode enabled, only works if block connections without VPN is disabled, no matter if compatibility mode is enabled or not.

**Comment by Gedsh** [comment] 2024-11-15 17:52
Fixed via https://github.com/Gedsh/InviZible/commit/5aee5ff127e99d4ef39db7a54b96c44a587b8633

**Closed by Gedsh** 2024-11-15 17:52 UTC
