### ISSUE TITLE
Odoh Relays Issue 

### ISSUE THREAD

**Issue by ZenzoK90** [Gedsh/InviZible#325] opened 2024-12-20 18:47 UTC
Hello, 
I'm having an issue with the latest beta version and the problem is, Odoh Relay servers don't seem to be loading. Have been trying to figure out the issue myself but couldn't solve it. Except Odoh Relay, all the servers and dnscrypt relays are loading. But, couldn't understand why only odoh-relays are not showing and not being able to select it from the lists. 
Could you please check and solve this issue in the latest beta version. 
Thank you

**Comment by Gedsh** [comment] 2024-12-24 22:46
Hello,

I cannot reproduce your issue. Please check whether you have ODoH servers enabled in the DNSCrypt settings. You can also try clearing the cache in the DNSCrypt settings. If nothing helps, you can try resetting the app settings.

**Comment by ZenzoK90** [comment] 2024-12-26 18:02
> Hello,
> 
> I cannot reproduce your issue. Please check whether you have ODoH servers enabled in the DNSCrypt settings. You can also try clearing the cache in the DNSCrypt settings. If nothing helps, you can try resetting the app settings.

Odoh servers is enabled, tried clearing the cache also but didn't work. Though resetting the app does help to solve the issue but the problem comes back after tweaking the DNSCrypt settings.

**Comment by Gedsh** [comment] 2024-12-26 18:18
> when i click the OdoH server check boxes it takes me to DNSCrypt Relays instead

That's impossible.

> Though resetting the app does help to solve the issue but the problem comes back after tweaking the DNSCrypt settings.

What do you mean by tweaking the settings? Obviously, you have set something up wrong.

**Comment by ZenzoK90** [comment] 2024-12-28 15:56
> > Obviously, you have set something up wrong.
> Not at all. I just change the 'Skip Incompatible to true' from toml.file and do some changes from dnscrypt blocklist sections, that's all.
 The issue pops up just like that, I don't know why and I can't figure it out myself. 
Resetting the app does help, but after making some changes to the above mentioned sections, the problem comes back. Whether it's related to selecting multiple odoh relays or its because of setting up blocklist, I don't know.

**Comment by Gedsh** [comment] 2024-12-28 18:08
> I just change the 'Skip Incompatible to true'

I have changed this option and everything still works fine.

> after making some changes

I'm closing the issue as I can't reproduce it and you can't provide any valuable information to help me with this.

**Closed by Gedsh** 2024-12-28 18:08 UTC
