### ISSUE TITLE
Whitelisted Apps not working on Huawei phones sold without google services

### ISSUE THREAD

**Issue by AntonyNderitu** [Gedsh/InviZible#151] opened 2022-08-07 18:59 UTC
I have tried repeatedly in vain to get whitelisted apps such as **kdeconnect** and **nitroshare** to work on Huawei phones sold without google services.

They only seem to work when i stop Invizible. This issue is not there on earlier phones sold by Huawei with google services. Please assist to resolve this issue.

**Comment by Gedsh** [comment] 2022-08-09 22:58
The problem is definitely not in Google services. InviZible doesn't need them and doesn't use them.

I really can't help you with kdeconnect as I'm using Mint and don't want to install nearly a gigabyte of required dependencies.

Duplicate of https://github.com/Gedsh/InviZible/issues/119

**Comment by Gedsh** [comment] 2022-08-09 23:00
Duplicate of https://github.com/Gedsh/InviZible/issues/119

**Closed by Gedsh** 2022-08-09 23:00 UTC
