### ISSUE TITLE
use app both profile (main and shelter)

### ISSUE THREAD

**Issue by remigermain** [Gedsh/InviZible#122] opened 2022-01-16 17:05 UTC
Hello, I have a problem when I use this application in the shelter profile, it can not connect to tor and dnscrypt while it works at the same time in the main profile how can I fix this?

thanx for this amazing app !

**Comment by Gedsh** [comment] 2022-01-17 22:45
Duplicate of #82

> amazing app

Thanks!

**Closed by Gedsh** 2022-01-17 22:45 UTC
