### ISSUE TITLE
[BUG] Telegram Waiting for network

### ISSUE THREAD

**Issue by Generator** [Gedsh/InviZible#124] opened 2022-01-25 21:34 UTC
## Description
When using Invizible Pro in "VPN Mode", Telegram fails to connect (Waiting for network...) on network when changing networks.
Tested with other pVPN apps (e.g. PersonalDNSFilter) no issues with Telegram

## Steps to reproduce
* Start Invizible Pro on VPN Mode (no TOR, no I2P)
* Disable/Enable Wifi
* Open Telegram

**Info:**
Invizible Pro Beta: v1.5.2
[Nekogram](NekoX-Dev/NekoX): v8.4.4-rc02
Telegram FOSS: 8.4.2

**Comment by Gedsh** [comment] 2022-01-26 16:06
I cannot reproduce your issue. If you are using a firewall, try disabling it. If that doesn't help, please provide logs. Menu -> Logs -> Collect logs.

**Comment by Generator** [comment] 2022-02-01 13:47
Logs done with clean install, with same results
[InvizibleLogs.txt.zip](https://github.com/Gedsh/InviZible/files/7978878/InvizibleLogs.txt.zip)

**Comment by Gedsh** [comment] 2022-02-03 10:46
I don't see apps trying to connect to the internet after you enabling Wi-Fi. 

Actually I don't see any problems in your log.

There may be a problem with your router. Please try enabling Bypass LAN addresses in Fast Settings.

**Comment by Generator** [comment] 2022-02-03 14:02
> There may be a problem with your router. 
This issue only happens in VPN mode, and similar apps don't have this issue, so the router isn't the problem.
In root mode there's no issue.

I'll try to log using adb and see what Telegram tries to connect to check connectivity.

**Comment by Gedsh** [comment] 2022-02-03 17:52
> Please try enabling Bypass LAN addresses in Fast Settings.

Have you tried this?

**Comment by Generator** [comment] 2022-02-03 18:09
Yes, with same results

**Comment by Gedsh** [comment] 2022-02-03 18:19
So currently I have no idea what is the problem with Telegram.

**Comment by Generator** [comment] 2022-02-03 21:44
Made some logs, couldn't find any issue.
Steps made: Disable WiFi, start logging, enable wifi.

logcat (nekox.messenger and pan.alexander.tordnscrypt)
[logcat.txt](https://github.com/Gedsh/InviZible/files/7998461/logcat.txt)

NekoX logs from app (Settings > Send logs)
[NekoX-1643923614019.log](https://github.com/Gedsh/InviZible/files/7998464/NekoX-1643923614019.log)

**Comment by Gedsh** [comment] 2022-02-05 13:45
I don't see anything interesting in these logs.

**Comment by Generator** [comment] 2022-08-22 13:26
This issue also affects other apps like [Syncthing-Fork](https://f-droid.org/en/packages/com.github.catfriend1.syncthingandroid/) and reported by a friend on a Xiaomi Mi Box S that **Netflix** also don't connect to network.

Syncthing execution conditions set to Wifi only. 
Like Telegram the app only reconnects to network if manually restarted

**Comment by Gedsh** [comment] 2022-08-22 22:09
I still can't reproduce your issue. And it seems to be rare as I don't hear the same issues from other users when only DNSCrypt is enabled.

**Comment by 0xlne** [comment] 2022-11-04 02:04
I can confirm a similar issue with different Telegram clients (example: NekoX), but not wih any other apps. Might be a TG specific issue like a hardcoded ttl which is too long.

**Comment by Gedsh** [comment] 2024-04-22 11:43
Fixed via 43819456d25417f2ddb8a7dc57bb9de071a0901e

**Closed** 2024-04-22 11:43 UTC
