### ISSUE TITLE
[Feature Request] add lokinet Internet

### ISSUE THREAD

**Issue by Pantyhose-X** [Gedsh/InviZible#118] opened 2021-12-27 15:36 UTC
[Lokinet](https://github.com/oxen-io/lokinet) is an anonymous, decentralized and IP based overlay network for the internet.
Lokinet Internet is safer than TOR

**Comment by Gedsh** [comment] 2021-12-30 19:29
Duplicate of #90

**Closed by Gedsh** 2021-12-30 19:29 UTC
